[build]
  command = "yarn build-storybook"
  publish = "storybook-static/"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "2.4.1"
  YARN_FLAGS = "--version"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
