name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Yarn version
        run: yarn --version

      - uses: actions/setup-node@master
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Configure Git User
        run: |
          git config --global user.email "ci@graveflex.com"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: Install Dependencies
        run: yarn install

      - name: Release Packages
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
