name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Configure Git User
        run: |
          git config --global user.email "ci@graveflex.com"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: Install Dependencies
        run: yarn install
        
      - name: Authenticate with Registry
        run: |
          echo "@refract-ui:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release Packages
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
